name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: registry.lukestoodley.com
          username: ${{ secrets.REG_USER }}
          password: ${{ secrets.REG_PASS }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: registry.lukestoodley.com/cryostat/docs:latest